version: "3.1"
services:
  back-end:
    image: ykassa-backend:latest
    container_name: back-end
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8091:8091"
    depends_on:
      - mongo-db
    environment:
      DB_USERNAME: "usrDev"
      DB_PASSWORD: "pasDev"
      DB_HOST: mongo-db
      DB_PORT: 27017
      DB_NAME: "yookassa"
      SWAGGER_SERVER: "http://localhost:8091"
      API_KEY_YOOKASSA: "test_ZZoaPUYfjWpRbeLGJyom6plQiRuaTOYml8_TrwnQeGk"
      ID_MAGAZINE_YOOKASSA: "367632"
      YOOKASSA_CREATE_URL: "https://api.yookassa.ru/v3/payments"
      RETURN_URL: "https://www.example.com/return_url"
    networks:
      - ykassa-webeffector

  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: usr
      MONGO_INITDB_ROOT_PASSWORD: pas
      MONGO_INITDB_USERNAME: usrDev
      MONGO_INITDB_PASSWORD_FILE: pasDev
      MONGO_INITDB_DATABASE: yookassa
    volumes:
      - ./mongo-scripts/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - ykassa-webeffector

networks:
  ykassa-webeffector:
    driver: bridge
